drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
drop table Article if exists
drop table Site if exists
drop sequence if exists hibernate_sequence
